// Generated by scripts/gen-types.mjs from docs/contracts/api-v1. Do not edit.
/* eslint-disable */

/** The inspector's agent page: genome, runs newest first, verdicts */
export type AgentView = {
  configuration_id: CommonUuid;
  genome: Configuration | null;
  runs: {
    items: Run[];
    next_cursor: CommonCursor;
  };
  forecasts: {
    items: Forecast[];
    next_cursor: CommonCursor;
  };
};

/** One digest entry as a rater sees it before rating */
export type BlindedEntry = {
  paper_hash: CommonSha256;
  digest_entry_id: CommonUuid;
  title: string;
  abstract: string;
};

/** The genome an owner command admitted or retired */
export type CommandResult = {
  configuration_id: CommonUuid;
};

export type CommonCsrfToken = string;

export type CommonCursor = string | null;

export type CommonEmphasisFields = {
  items: Array<"probability_assignment_rule" | "prompt" | "read_policy" | "scan_policy">;
  next_cursor: null;
};

export type CommonIsland = "cs" | "quant-ph" | "q-bio";

export type CommonNotice = "Automated output. Not a scientific claim authored by any person.";

export type CommonSha256 = string;

export type CommonUtcDate = string;

export type CommonUtcInstant = string;

export type CommonUuid = string;

/** One admitted genome as the population store holds it */
export type Configuration = {
  configuration_id: CommonUuid;
  configuration_hash: CommonSha256;
  lineage_id: string;
  island: CommonIsland;
  founder: boolean;
  infra_hash: CommonSha256;
  parent_hash: CommonSha256 | null;
  parts: Array<{
    part: string;
    value: string;
    value_hash: CommonSha256;
  }>;
  admission: {
    disposition: string;
    profile_hash: string | null;
  };
  admitted_at: CommonUtcInstant;
  archive: null | {
    cycle_id: string;
    skill: number | null;
    resolved_claim_count: number;
    profile_hash: string | null;
    archived_at: CommonUtcInstant;
  };
};

export type EmbeddingViewPoint = number[];

/** One paper family's current embedding view, as stored where its vectors were published, owner only (#298) */
export type EmbeddingView = {
  paper_id: CommonUuid;
  paper_version_id: CommonUuid;
  representation_hash: CommonSha256;
  extraction_hash: CommonSha256;
  chunk_policy: "passages-384-64-v1";
  coverage: string;
  dims: number;
  overview: {
    /** The overview vector, dims coordinates rounded to 4 decimals. */
    vector: number[];
    /** The overview's coordinate values in 48 equal-width bins from min to max, the last bin closed. */
    histogram: {
      bins: 48;
      min: number;
      max: number;
      counts: number[];
    };
    pc: EmbeddingViewPoint;
  };
  passages: {
    items: Array<{
      order: number;
      section_path: string[];
      section_order: number;
      tokens: number;
      char_start: number;
      char_end_exclusive: number;
      /** The passage's text with whitespace collapsed, at most 120 characters, then an ellipsis where cut. */
      excerpt: string;
      cos_overview: number;
      /** 96 magnitudes: the summed absolute coordinates of each consecutive run of dims/96 coordinates, 3 decimals. */
      bins: number[];
      pc: EmbeddingViewPoint;
    }>;
    next_cursor: null;
  };
  similarity: {
    order: "passage order";
    /** Passage-to-passage cosine, one row and one column per passage in passage order, 3 decimals. */
    rows: Array<number[]>;
  };
  /** PCA over the paper's overview and passage vectors; each component's largest loading is positive. */
  projection: {
    method: "pca";
    /** The two components' shares of the total variance. */
    explained: number[];
  };
  neighbors: {
    /** Up to ten other families nearest by overview cosine over the published index, each family by its first public version; ties by family id. */
    items: Array<{
      paper_id: CommonUuid;
      title: string;
      cos: number;
      /** True when both first public times are known and the neighbor's is strictly earlier. */
      earlier: boolean;
    }>;
    next_cursor: null;
  };
  /** The view's provenance (SR-23): the same inputs rebuild the same bytes. */
  derived_from: {
    /** The overview artifact's hash where the publish path stores one; null otherwise, the overview vector being part of the passage index entry. */
    overview_hash: CommonSha256 | null;
    /** SHA-256 of the published index entry's canonical JSON. */
    passage_index_hash: CommonSha256;
    /** SHA-256 of the canonical JSON of the family, version and overview vector of every candidate the neighbors were ranked over. */
    neighbor_index_hash: CommonSha256;
    component_version: "embedding-view-v1";
  };
};

/** Success envelope of every /api/v1 response */
export type Envelope = {
  contract: "1";
  data: Record<string, unknown>;
};

/** Refusal envelope of every /api/v1 response */
export type Error = {
  contract: "1";
  error: {
    /** 400 and 422 invalid_request, 401 unauthenticated, 403 forbidden, 404 not_found, 409 state_conflict, 502 not_saved, 503 unavailable. */
    code: "invalid_request" | "unauthenticated" | "forbidden" | "not_found" | "state_conflict" | "not_saved" | "unavailable";
    message: string;
    /** The request field or header the refusal names, or null. */
    field: string | null;
  };
};

/** One sealed claim with its latest resolution, or null while pending */
export type Forecast = {
  submission_id: CommonUuid;
  run_id: CommonUuid;
  question_id: CommonUuid;
  confidence: number;
  horizon: CommonUtcInstant;
  sealed_at: CommonUtcInstant;
  resolver_id: string;
  resolver_version: number;
  resolution: null | {
    resolution_id: CommonUuid;
    status: string;
    resolver_id: string;
    resolver_build_digest: string;
    resolution_version: number;
    resolved_at: CommonUtcInstant;
  };
};

export type HealthState = "healthy" | "waiting" | "failed" | "operator_repair";

/** The platform health monitor's report (#254) */
export type Health = {
  state: HealthState;
  checked_at: CommonUtcInstant;
  checks: Array<{
    name: string;
    state: HealthState;
    detail: string;
  }>;
};

/** The models page: one typed manifest artifact */
export type ManifestView = {
  manifest: {
    manifest_hash: CommonSha256;
    artifact_hash: CommonSha256;
    manifest_kind: string;
    media_type: string;
    byte_length: number;
    created_at: CommonUtcInstant;
    fields: Record<string, unknown>;
  };
};

/** One owner admission: an edit naming its source, or a seed */
export type OwnerAdmission = {
  configuration_id: CommonUuid;
  owner_id: CommonUuid;
  kind: "edit" | "seed";
  source_configuration_id: CommonUuid | null;
  requested_at: CommonUtcInstant;
};

/** The owner's agent page: genome, owner history, and the inspector's runs and verdicts */
export type OwnerAgentView = {
  genome: OwnerGenome;
  emphasis_fields: CommonEmphasisFields;
  admission: OwnerAdmission | null;
  retirement: Retirement | null;
  csrf_token: CommonCsrfToken;
  inspected?: AgentView;
};

export type OwnerCostsIslandOrNone = CommonIsland | null;

export type OwnerCostsTotals = {
  priced_micros: number;
  priced_runs: number;
  unpriced_runs: number;
  unpriced_input_tokens: number;
  unpriced_output_tokens: number;
};

/** Settled inference spend of one UTC day and its month against the launch profile's caps, owner only (#251) */
export type OwnerCosts = {
  day: CommonUtcDate;
  month: string;
  source: "settlements";
  caps: {
    daily_cap_micros: number;
    monthly_cap_micros: number;
    jev_daily_sublimit_micros: number;
    jev_daily_sublimit_source: "profile_constant";
    funded: boolean;
    paid_execution_enabled: boolean;
  };
  today: OwnerCostsTotals;
  month_to_date: OwnerCostsTotals;
  by_island: {
    items: Array<{
      island: OwnerCostsIslandOrNone;
      priced_micros: number;
      priced_runs: number;
      unpriced_runs: number;
      unpriced_input_tokens: number;
      unpriced_output_tokens: number;
    }>;
    next_cursor: null;
  };
  by_configuration: {
    items: Array<{
      configuration_id: CommonUuid;
      island: OwnerCostsIslandOrNone;
      priced_micros: number;
      priced_runs: number;
      unpriced_runs: number;
      unpriced_input_tokens: number;
      unpriced_output_tokens: number;
    }>;
    next_cursor: null;
  };
};

export type OwnerDigestRated = {
  entry_id: CommonUuid;
  paper_hash: CommonSha256;
  origin: "population" | "random_control" | "service";
  display_position: number;
  service_source: string | null;
  candidate_pool_hash: CommonSha256 | null;
  inclusion_probability: number | null;
  nominations: Array<{
    configuration_id: CommonUuid;
    submission_id: CommonUuid;
    preference: number;
  }>;
  rated: true;
};

export type OwnerDigestUnrated = {
  entry_id: CommonUuid;
  paper_hash: CommonSha256;
  display_position: number;
  rated: false;
};

/** A stored digest as the owner, who is also a rater, may see it (SR-25, #255) */
export type OwnerDigest = {
  digest_hash: CommonSha256;
  batch_id: string;
  island: CommonIsland;
  source_watermark: number;
  shuffle_seed: string;
  built_at: CommonUtcInstant;
  entries: Array<OwnerDigestUnrated | OwnerDigestRated>;
};

/** One genome's identity, as the owner's edit and seed forms prefill from it */
export type OwnerGenome = {
  configuration_id: CommonUuid;
  configuration_hash: CommonSha256;
  island: CommonIsland;
  founder: boolean;
  lineage_id: string;
  emphasis: {
    prompt: string;
    scan_policy: string;
    read_policy: string;
    probability_assignment_rule: string;
  };
};

/** One island's stored genomes, founders first, with counts of their runs and settled cost, owner only (#344) */
export type OwnerIsland = {
  island: CommonIsland;
  genomes: {
    items: Array<{
      configuration_id: CommonUuid;
      configuration_hash: CommonSha256;
      lineage_id: string;
      founder: boolean;
      admission: "seeded" | "accepted";
      admitted_at: CommonUtcInstant;
      runs: number;
      void_runs: number;
      priced_runs: number;
      cost_micros: number;
      last_run_at: CommonUtcInstant | null;
    }>;
    next_cursor: null;
  };
};

/** Each island the population store holds, with counts of its stored genomes and their runs, owner only (#344) */
export type OwnerIslands = {
  islands: {
    items: Array<{
      island: CommonIsland;
      genomes: number;
      founders: number;
      lineages: number;
      runs: number;
      last_run_at: CommonUtcInstant | null;
    }>;
    next_cursor: null;
  };
};

/** The owner actions app's sign-in view */
export type OwnerLogin = Record<string, unknown>;

export type OwnerPaperCard = {
  snapshot_hash: CommonSha256;
  paper_version_id: CommonUuid;
  card_hash: CommonSha256;
  /** The pinned card record exactly as stored (RD-01). */
  card: Record<string, unknown>;
};

export type OwnerPaperEnding = {
  state: "submitted" | "void";
  /** The void reason; null for a submitted run. */
  reason: string | null;
  ended_at: CommonUtcInstant;
  /** The accepted submission; null for a void run. */
  submission: null | OwnerPaperSubmission;
};

export type OwnerPaperRequest = {
  request_id: CommonUuid;
  run_id: CommonUuid;
  snapshot_hash: CommonSha256;
  status: "requested" | "acquiring" | "acquired" | "failed" | "refused";
  reason: string | null;
  requested_at: CommonUtcInstant;
  started_at: CommonUtcInstant | null;
  paper_version_id: CommonUuid | null;
};

export type OwnerPaperRun = {
  run_id: CommonUuid;
  batch_id: string;
  paper_id: string;
  configuration_id: CommonUuid;
  attempt: number;
  genome_hash: CommonSha256;
  seed: number;
  snapshot_hash: CommonSha256;
  budgets: {
    spend_micros: number;
  };
  allowed_tools: string[];
  model_identity: Record<string, unknown>;
  checkpoint_dates: CommonUtcDate[];
  created_at: CommonUtcInstant;
  /** The model's turns by hash, in order. */
  events: Array<{
    attempt: number;
    ordinal: number;
    kind: string;
    payload_hash: CommonSha256;
    recorded_at: CommonUtcInstant;
  }>;
  /** Null while the run is active. */
  ending: null | OwnerPaperEnding;
  /** The run's sealed claims, each with its latest verdict or null while pending. */
  outcomes: Forecast[];
  /** The path of this run's trace (owner-run-trace.json). */
  trace: string;
};

export type OwnerPaperSubmission = {
  submission_id: CommonUuid;
  accepted_at: CommonUtcInstant;
  forecasts: Array<{
    question_id: CommonUuid;
    probability: number;
    rationale: string;
    evidence_ids: CommonSha256[];
  }>;
  nomination: null | {
    paper_id: string;
    recommend: boolean;
    preference: number;
    rationale: string;
  };
};

/** Everything the agents saw of one paper family, from stored records, owner only (#301) */
export type OwnerPaper = {
  paper_id: CommonUuid;
  /** The path of the family's embedding view (embedding-view.json), 404 until one is published. */
  embedding_view: string;
  /** True when a stored paper request acquired the family; false when it came in by the population rule. */
  acquired_on_request: boolean;
  requests: {
    /** Every stored paper request for the family, oldest first, each naming the run that asked. */
    items: OwnerPaperRequest[];
    next_cursor: null;
  };
  cards: {
    /** For each snapshot a run on this page received, the card record it pins for the family: the record query_cards returns to a run, head probabilities included. */
    items: OwnerPaperCard[];
    next_cursor: null;
  };
  runs: {
    /** The runs that read the family, newest first, 50 to a page. */
    items: OwnerPaperRun[];
    next_cursor: CommonCursor;
  };
};

/** Each island and ISO week holding a stored digest or rating, with counts of its stored records, owner only (#344) */
export type OwnerReports = {
  reports: {
    items: Array<{
      island: CommonIsland;
      iso_week: string;
      digests: number;
      entries: number;
      ratings: number;
      credits: number;
    }>;
    next_cursor: null;
  };
};

export type OwnerRunEventCall = {
  call_sequence: number;
  call_id: CommonUuid;
  tool: string;
  request_hash: CommonSha256;
  decision: "admitted" | "refused";
  reason: string | null;
  started_at: CommonUtcInstant;
  request: OwnerRunTracePayload;
  terminal: null | OwnerRunTraceTerminal;
};

export type OwnerRunEventSettlement = {
  provider: string;
  model: string;
  input_tokens: number;
  output_tokens: number;
  usage_source: "provider" | "loop_count";
  cost_micros: number | null;
  settled_at: CommonUtcInstant;
};

/** One live run event: the data of one server-sent event on the owner's live run stream (#327) */
export type OwnerRunEvent = {
  /** The event's ledger sequence, also its server-sent event id; Last-Event-ID resumes after it. */
  id: string;
  /** call: a tool call was recorded; terminal: its response or error was; ending: the run submitted or voided; settlement: its tokens and cost were settled. */
  kind: "call" | "terminal" | "ending" | "settlement";
  run_id: CommonUuid;
  /** The family the run read; null for a run with no paper slot. */
  paper_id: null | CommonUuid;
  /** The island of the run's configuration; null when storage holds no genome for it. */
  island: string | null;
  /** For call and terminal events: the call as the paper page's trace renders it (owner-run-trace.json), with a null terminal on a call event. Null otherwise. */
  call: null | OwnerRunEventCall;
  /** For an ending event: how the run ended, as the paper page shows it. Null otherwise. */
  ending: null | OwnerPaperEnding;
  /** For a settlement event: the run's settlement as stored. Null otherwise. */
  settlement: null | OwnerRunEventSettlement;
};

export type OwnerRunTraceCall = {
  call_sequence: number;
  call_id: CommonUuid;
  /** Any recorded tool name, admitted or not; an unknown one is shown, never dropped. */
  tool: string;
  request_hash: CommonSha256;
  decision: "admitted" | "refused";
  /** Why a refused call was refused; null for an admitted one. */
  reason: string | null;
  started_at: CommonUtcInstant;
  /** The call as the run sent it: tool and arguments. */
  request: OwnerRunTracePayload;
  /** Null for a refused call or one not yet answered. */
  terminal: null | OwnerRunTraceTerminal;
  /** deep_reads, images and tool_calls left once this call and every earlier one were charged. Token and spend budgets are charged by model turns and are not here. */
  remaining_budgets: {
    deep_reads?: number;
    images?: number;
    tool_calls?: number;
  };
};

export type OwnerRunTracePayload = null | {
  /** The stored artifact holding the exact bytes. */
  artifact_hash: CommonSha256;
  /** True when the payload was cut to 256 KiB; the call's hash is still of the whole. */
  truncated: boolean;
  /** The stored bytes as UTF-8; a byte sequence that is not UTF-8 reads as U+FFFD. */
  text: string;
};

export type OwnerRunTraceTerminal = {
  outcome: "response" | "error";
  response_hash: CommonSha256;
  error_code: string | null;
  retrieved_ids: CommonSha256[];
  budget_deltas: {
    deep_reads?: number;
    images?: number;
    tool_calls?: number;
    context_tokens?: number;
    generation_tokens?: number;
    timeout_seconds?: number;
    retries?: number;
    wall_time_seconds?: number;
    spend_micros?: number;
  };
  ended_at: CommonUtcInstant;
  /** The envelope the run received. */
  response: OwnerRunTracePayload;
};

/** One run and every tool call it made, in call order, owner only (#301) */
export type OwnerRunTrace = {
  run: OwnerPaperRun;
  calls: {
    items: OwnerRunTraceCall[];
    next_cursor: null;
  };
};

/** The population page: every admitted genome, newest admission first */
export type Population = {
  configurations: {
    items: Configuration[];
    next_cursor: CommonCursor;
  };
};

/** The session rater's preference credit of one ISO week, a share per row and no total (IN-43, #252) */
export type RatingCredit = {
  credits: {
    items: Array<{
      rating_id: CommonUuid;
      genome_hash: CommonSha256;
      share: number;
    }>;
    next_cursor: null;
  };
};

/** A rater's digest, blinded (SR-21, SR-22, SR-25) */
export type RatingDigest = {
  notice: CommonNotice;
  rows: {
    items: BlindedEntry[];
    next_cursor: CommonCursor;
  };
  csrf_token: CommonCsrfToken;
};

/** The rating app's sign-in view */
export type RatingLogin = {
  notice: CommonNotice;
};

/** The session rater's own ratings of one batch (IN-10, #252) */
export type RatingOwnRatings = {
  ratings: {
    items: Array<{
      rating_id: CommonUuid;
      digest_entry_id: CommonUuid;
      paper_hash: CommonSha256;
      value: "like" | "dislike" | "skip";
      rated_at: CommonUtcInstant;
    }>;
    next_cursor: null;
  };
};

/** A rating storage accepted (IN-10) */
export type RatingRecorded = {
  rating_id: CommonUuid;
  rated_at: CommonUtcInstant;
};

export type ReportViewComparison = {
  comparator: "random_control" | "service";
  population_likes: number;
  population_decided: number;
  comparator_likes: number;
  comparator_decided: number;
  population_rate: number | null;
  comparator_rate: number | null;
  weeks: number;
  interval: {
    method: string;
    method_version: number;
    resamples: number;
    seed: number;
    lower_tail: number;
    upper_tail: number;
    support_count: number;
    support_hash: string;
    estimate: number | null;
    low: number | null;
    high: number | null;
    disposition: string;
  };
  verdict: {
    verdict: string;
    low: number | null;
    high: number | null;
    favorable_direction: string;
    minimum_effect: number | null;
    minimum_effect_pass: boolean | null;
  };
};

export type ReportViewGenomeRow = {
  genome_hash: CommonSha256;
  founder: boolean;
  skills: Array<{
    target_id: string;
    skill: number | null;
    support_count: number;
    disposition: string;
  }>;
  preference_credit: number;
  credited_entries: number;
};

export type ReportViewMigration = {
  child_hash: CommonSha256;
  source_island: CommonIsland;
  source_hash: CommonSha256;
};

/** The weekly island report page (FT-26) */
export type ReportView = {
  notice: CommonNotice;
  comparator_names: {
    random_control: string;
    service: string;
  };
  report: {
    island: CommonIsland;
    iso_week: string;
    rows: ReportViewGenomeRow[];
    preference_reason: string | null;
    comparisons: ReportViewComparison[];
    migrations: ReportViewMigration[];
  };
};

/** One owner request that a genome leave the active population */
export type Retirement = {
  configuration_id: CommonUuid;
  owner_id: CommonUuid;
  requested_at: CommonUtcInstant;
};

/** The owner retrospective: every admission and retirement, newest first */
export type Retrospective = {
  admissions: {
    items: OwnerAdmission[];
    next_cursor: CommonCursor;
  };
  retirements: {
    items: Retirement[];
    next_cursor: CommonCursor;
  };
  csrf_token: CommonCsrfToken;
};

/** The run page: a run, its events and the claims it sealed as itself */
export type RunView = {
  run: Run;
  submissions: {
    items: Submission[];
    next_cursor: CommonCursor;
  };
};

/** One stored run (storage GET /v1/runs/{run_id}) */
export type Run = {
  run_id: CommonUuid;
  batch_id: string;
  paper_id: string;
  configuration_id: CommonUuid;
  attempt: number;
  genome_hash: CommonSha256;
  seed: number;
  snapshot_hash: CommonSha256;
  budgets: {
    spend_micros: number;
  };
  allowed_tools: string[];
  model_identity: Record<string, unknown>;
  checkpoint_dates: CommonUtcDate[];
  created_at: CommonUtcInstant;
  events?: Array<{
    attempt: number;
    ordinal: number;
    kind: string;
    payload_hash: CommonSha256;
    recorded_at: CommonUtcInstant;
  }>;
};

/** The seed form, blank or copied from a template genome */
export type SeedView = {
  emphasis_fields: CommonEmphasisFields;
  copied: OwnerGenome | null;
  csrf_token: CommonCsrfToken;
};

/** A session revoked by POST /api/v1/logout */
export type SessionEnded = {
  authenticated: false;
};

/** A session opened by POST /api/v1/login */
export type Session = {
  authenticated: true;
  expires_at: CommonUtcInstant;
  csrf_token: CommonCsrfToken;
};

/** One claim a run sealed as itself */
export type Submission = {
  submission_id: CommonUuid;
  sheet_hash: CommonSha256;
  question_id: CommonUuid;
  status: string;
  confidence: number | null;
  horizon: CommonUtcInstant | null;
  reason: string | null;
  sealed_at: CommonUtcInstant;
  evidence_hashes: CommonSha256[];
};

/** Every response schema by its file name, as endpoints.json cites it. */
export interface SchemaTypes {
  "agent-view.json": AgentView;
  "blinded-entry.json": BlindedEntry;
  "command-result.json": CommandResult;
  "configuration.json": Configuration;
  "embedding-view.json": EmbeddingView;
  "envelope.json": Envelope;
  "error.json": Error;
  "forecast.json": Forecast;
  "health.json": Health;
  "manifest-view.json": ManifestView;
  "owner-admission.json": OwnerAdmission;
  "owner-agent-view.json": OwnerAgentView;
  "owner-costs.json": OwnerCosts;
  "owner-digest.json": OwnerDigest;
  "owner-genome.json": OwnerGenome;
  "owner-island.json": OwnerIsland;
  "owner-islands.json": OwnerIslands;
  "owner-login.json": OwnerLogin;
  "owner-paper.json": OwnerPaper;
  "owner-reports.json": OwnerReports;
  "owner-run-event.json": OwnerRunEvent;
  "owner-run-trace.json": OwnerRunTrace;
  "population.json": Population;
  "rating-credit.json": RatingCredit;
  "rating-digest.json": RatingDigest;
  "rating-login.json": RatingLogin;
  "rating-own-ratings.json": RatingOwnRatings;
  "rating-recorded.json": RatingRecorded;
  "report-view.json": ReportView;
  "retirement.json": Retirement;
  "retrospective.json": Retrospective;
  "run-view.json": RunView;
  "run.json": Run;
  "seed-view.json": SeedView;
  "session-ended.json": SessionEnded;
  "session.json": Session;
  "submission.json": Submission;
}

/** The route list of endpoints.json. */
export const ENDPOINTS = [
  { app: "rating", method: "GET", path: "/api/v1/login", status: 200, schema: "rating-login.json" },
  { app: "rating", method: "POST", path: "/api/v1/login", status: 200, schema: "session.json" },
  { app: "rating", method: "POST", path: "/api/v1/logout", status: 200, schema: "session-ended.json" },
  { app: "rating", method: "GET", path: "/api/v1/digest", status: 200, schema: "rating-digest.json" },
  { app: "rating", method: "POST", path: "/api/v1/ratings", status: 201, schema: "rating-recorded.json" },
  { app: "rating", method: "GET", path: "/api/v1/ratings", status: 200, schema: "rating-own-ratings.json" },
  { app: "rating", method: "GET", path: "/api/v1/credit", status: 200, schema: "rating-credit.json" },
  { app: "inspector", method: "GET", path: "/api/v1/runs/{run_id}", status: 200, schema: "run-view.json" },
  { app: "inspector", method: "GET", path: "/api/v1/agents", status: 200, schema: "population.json" },
  { app: "inspector", method: "GET", path: "/api/v1/agents/{configuration_id}", status: 200, schema: "agent-view.json" },
  { app: "inspector", method: "GET", path: "/api/v1/models/{manifest_hash}", status: 200, schema: "manifest-view.json" },
  { app: "report", method: "GET", path: "/api/v1/reports/{island}/{iso_week}", status: 200, schema: "report-view.json" },
  { app: "actions", method: "GET", path: "/api/v1/login", status: 200, schema: "owner-login.json" },
  { app: "actions", method: "POST", path: "/api/v1/login", status: 200, schema: "session.json" },
  { app: "actions", method: "POST", path: "/api/v1/logout", status: 200, schema: "session-ended.json" },
  { app: "actions", method: "GET", path: "/api/v1/retrospective", status: 200, schema: "retrospective.json" },
  { app: "actions", method: "GET", path: "/api/v1/health", status: 200, schema: "health.json" },
  { app: "actions", method: "GET", path: "/api/v1/costs", status: 200, schema: "owner-costs.json" },
  { app: "actions", method: "GET", path: "/api/v1/islands", status: 200, schema: "owner-islands.json" },
  { app: "actions", method: "GET", path: "/api/v1/islands/{island}", status: 200, schema: "owner-island.json" },
  { app: "actions", method: "GET", path: "/api/v1/reports", status: 200, schema: "owner-reports.json" },
  { app: "actions", method: "GET", path: "/api/v1/papers/{paper_id}/embedding", status: 200, schema: "embedding-view.json" },
  { app: "actions", method: "GET", path: "/api/v1/owner/papers/{paper_id}", status: 200, schema: "owner-paper.json" },
  { app: "actions", method: "GET", path: "/api/v1/owner/runs/live", status: 200, schema: "owner-run-event.json" },
  { app: "actions", method: "GET", path: "/api/v1/owner/runs/{run_id}/trace", status: 200, schema: "owner-run-trace.json" },
  { app: "actions", method: "GET", path: "/api/v1/agents", status: 200, schema: "population.json" },
  { app: "actions", method: "GET", path: "/api/v1/runs/{run_id}", status: 200, schema: "run-view.json" },
  { app: "actions", method: "GET", path: "/api/v1/models/{manifest_hash}", status: 200, schema: "manifest-view.json" },
  { app: "actions", method: "GET", path: "/api/v1/digests/{digest_hash}", status: 200, schema: "owner-digest.json" },
  { app: "actions", method: "GET", path: "/api/v1/agents/{configuration_id}", status: 200, schema: "owner-agent-view.json" },
  { app: "actions", method: "POST", path: "/api/v1/agents/{configuration_id}/admit", status: 201, schema: "command-result.json" },
  { app: "actions", method: "POST", path: "/api/v1/agents/{configuration_id}/retire", status: 200, schema: "command-result.json" },
  { app: "actions", method: "GET", path: "/api/v1/seed", status: 200, schema: "seed-view.json" },
  { app: "actions", method: "POST", path: "/api/v1/seed", status: 201, schema: "command-result.json" },
] as const;
