// Generates src/api/schema.gen.ts from the /api/v1 JSON Schemas in
// docs/contracts/api-v1. The backend owns every data shape; this output is
// checked in so a schema change fails the typecheck and the currency test.
//
//   node scripts/gen-types.mjs          write the file
//   node scripts/gen-types.mjs --check  exit 1 if the checked-in file is stale

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const SCHEMA_DIR = resolve(here, "../../docs/contracts/api-v1");
export const OUTPUT = resolve(here, "../src/api/schema.gen.ts");

const pascal = (s) =>
  s
    .replace(/\.json$/, "")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

const typeName = (file, def) => pascal(file) + (def ? pascal(def) : "");

let schemaDir = SCHEMA_DIR;
const loaded = new Map();
const load = (file) => {
  if (!loaded.has(file)) loaded.set(file, JSON.parse(readFileSync(join(schemaDir, file), "utf8")));
  return loaded.get(file);
};

// A $ref to a whole file or a $defs entry names its generated type. Any other
// pointer (for example run.json#/properties/run_id) is resolved and inlined.
function emitRef(ref, file, indent) {
  const [target, pointer] = ref.split("#");
  const owner = target === "" ? file : target;
  if (!pointer) return typeName(owner);
  const match = /^\/\$defs\/([^/]+)$/.exec(pointer);
  if (match) return typeName(owner, match[1]);
  let node = load(owner);
  for (const part of pointer.split("/").slice(1)) {
    node = node?.[part.replace(/~1/g, "/").replace(/~0/g, "~")];
  }
  if (node === undefined) throw new Error(`${file}: unresolved $ref ${ref}`);
  return emit(node, owner, indent);
}

const key = (k) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k));

function emit(schema, file, indent) {
  if (schema === true || schema === undefined) return "unknown";
  if (schema === false) return "never";
  if (schema.$ref) return emitRef(schema.$ref, file, indent);
  if ("const" in schema) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (schema.oneOf || schema.anyOf) {
    return (schema.oneOf ?? schema.anyOf).map((s) => emit(s, file, indent)).join(" | ");
  }
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  if (types.length > 1) {
    return types.map((t) => emit({ ...schema, type: t }, file, indent)).join(" | ");
  }
  switch (types[0]) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array": {
      const item = emit(schema.items, file, indent);
      return /^[A-Za-z0-9_]+$/.test(item) ? `${item}[]` : `Array<${item}>`;
    }
    case "object":
    case undefined:
      return emitObject(schema, file, indent);
    default:
      throw new Error(`${file}: unsupported type ${types[0]}`);
  }
}

function emitObject(schema, file, indent) {
  const props = schema.properties ?? {};
  const names = Object.keys(props);
  const extra = schema.additionalProperties;
  if (names.length === 0) {
    if (extra && typeof extra === "object") return `Record<string, ${emit(extra, file, indent)}>`;
    return "Record<string, unknown>";
  }
  const required = new Set(schema.required ?? []);
  const pad = "  ".repeat(indent + 1);
  const lines = names.map((n) => {
    const doc = props[n].description ? `${pad}/** ${props[n].description.replace(/\*\//g, "*\\/")} */\n` : "";
    return `${doc}${pad}${key(n)}${required.has(n) ? "" : "?"}: ${emit(props[n], file, indent + 1)};`;
  });
  return `{\n${lines.join("\n")}\n${"  ".repeat(indent)}}`;
}

export function generate(dir = SCHEMA_DIR) {
  schemaDir = dir;
  loaded.clear();
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".json") && f !== "endpoints.json")
    .sort();
  const out = [
    "// Generated by scripts/gen-types.mjs from docs/contracts/api-v1. Do not edit.",
    "/* eslint-disable */",
    "",
  ];
  for (const file of files) {
    const schema = JSON.parse(readFileSync(join(dir, file), "utf8"));
    for (const [def, sub] of Object.entries(schema.$defs ?? {}).sort(([a], [b]) => a.localeCompare(b))) {
      out.push(`export type ${typeName(file, def)} = ${emit(sub, file, 0)};`, "");
    }
    if (schema.type || schema.$ref || schema.oneOf || schema.properties) {
      if (schema.title) out.push(`/** ${schema.title} */`);
      out.push(`export type ${typeName(file)} = ${emit(schema, file, 0)};`, "");
    }
  }
  out.push("/** Every response schema by its file name, as endpoints.json cites it. */");
  out.push("export interface SchemaTypes {");
  for (const file of files) {
    const schema = JSON.parse(readFileSync(join(dir, file), "utf8"));
    if (schema.type || schema.$ref || schema.oneOf || schema.properties) {
      out.push(`  ${JSON.stringify(file)}: ${typeName(file)};`);
    }
  }
  out.push("}", "");
  const endpoints = JSON.parse(readFileSync(join(dir, "endpoints.json"), "utf8")).endpoints;
  out.push("/** The route list of endpoints.json. */");
  out.push("export const ENDPOINTS = [");
  for (const e of endpoints) {
    out.push(
      `  { app: ${JSON.stringify(e.app)}, method: ${JSON.stringify(e.method)}, path: ${JSON.stringify(e.path)}, status: ${e.status}, schema: ${JSON.stringify(e.schema)} },`,
    );
  }
  out.push("] as const;", "");
  return out.join("\n");
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const text = generate();
  if (process.argv.includes("--check")) {
    const current = readFileSync(OUTPUT, "utf8");
    if (current !== text) {
      console.error("src/api/schema.gen.ts is stale: run npm run gen:types");
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, text);
  }
}
